### ISSUE TITLE
Use disjoint-set data structure to store groups

### ISSUE THREAD

**Issue by mhelvens** [jokkebk/jgoboard#1]
This may be a bit silly, but ever since I learned about the [disjoint-set data structure](http://en.wikipedia.org/wiki/Disjoint-set_data_structure), I thought that if I ever wrote a go engine, I could use it to keep track of connected groups. ;-)

Basically, you would use it to rewrite [`Board#getGroup` ](https://github.com/jokkebk/jgoboard/blob/master/JGO/board.js#L262). Instead of re-calculating groups each time, you just consult the data structure, which is grown organically when a move is played. With a simple modification, you could simultaneously keep track of neighbors.

Anyway, performance of the engine is probably not a priority for you, but if you're enough of a computer science geek, you might want to go for it. Cheers!

**Comment by jokkebk** [comment]
That is a neat idea, especially since moves can only merge sets, never
split them. However, there is really no practical performance gain, as long
as the library is used for go board visualization and not Monte Carlo
simulations (for which Javascript would be a terrible idea from the start),
the maximum of few hundreds if's (almost full board group) would still
account only for 0.01 % or processor time. :)

**Comment by jokkebk** [comment]
Oh and thanks for the idea, in any case! :+1:

**Comment by mhelvens** [comment]
Oh, I agree. For a pure visualization library, the performance gain is negligible. In your position, I might do this just for the fun of it. But I understand that it's far from a priority, do go ahead and close the issue.

That said, is it unthinkable that someone would want to write a go AI in JavaScript? The choice of source and target language are almost independent these days, and I happen to like writing JavaScript code. Also, JS seems to be here to stay. Some JS engines are already quite competitive, performance wise, and I only expect this to get better.
